### ISSUE TITLE
Transaction hash contain "undefined" as string

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/budget-tracking#191]
If one of the properties is `undefined`, the hash string will contain `"undefined"` as a string. For example: `"2020-04-21T21:00:00.000Z_-1234.56_‏בני דרום מושב שיתופ(י)_undefined_mizrahi_123-123456"`

https://github.com/brafdlog/budget-tracking/blob/928929b72d6b24471a76ca7470f84cde8f12952f/src/backend/transactions/transactions.ts#L11-L15

Is this expected?

Need to discuss before changing.

**Comment by brafdlog** [comment]
Not very pretty.
But I don't think it makes much of a difference because this hash a value for the internal use of the system.
I am fine with fixing and fine with leaving as is.
One thing to note is that fixing this will cause these transactions to be created again.
Not a bug issue at this stage with the current level of usage

**Comment by baruchiro** [comment]
OK, I suggest to postpone this, and maybe reopen it someday.

We have others with more priority.
