### ISSUE TITLE
Merge with the israeli-bank-scrapers-desktop repo

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#51]
Project for issues we want to handle pre merge: https://github.com/brafdlog/budget-tracking/projects/4

Related issues:
- [x] Make the configManage use the crypto module and remove hard coded encryption key
- [x] Make the node code expose an api as defined [here](https://miro.com/app/board/iXjVOf3EJUs=)
- [x] Update the electron UI flow to work with two main flows - configure, run scraping as defined [here](https://miro.com/app/board/iXjVOf3EJUs=)
- [x] Make the electron UI work the node "library" code
- [x] Remove the Contributors part or hide it in a Menu or something #87 
- [x] Align filename #57

Post Merge Actions:
 - [ ] Decide how to release (by `Tag` or by pushing to `master`)
 - [ ] Copy relevant issues from `israeli-bank-scrapers-desktop`.
 - [ ] New repo/app name?
 - [ ] Check if there unused packages
 - [ ] Add MacOS to tests
 - [ ] Create Splash screen (until the renderer process loaded)
 - [ ] Set show browser in `configManager`? Define it for all importers?
 - [ ] Add ability to disable importer and exporter (and keep them configured)

**Comment by baruchiro** [comment]
Note that the folder `nuxt` contains the [Github Pages](https://baruchiro.github.io/israeli-bank-scrapers-desktop/), do you want to keep it?

I think the regular users need a beautiful webpage in Hebrew, with a big download button and help content.

But if you want to rethink that, maybe to use another technology...

**Comment by baruchiro** [comment]
About the file structure, I already started to reorg the project in https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/247, but it is not important, since I think the most of my code will move to BudgetTrackingApp, or just gone, and the rest of the code is the `components` folder.

**Comment by brafdlog** [comment]
Regarding the githup pages, you mean you wanted to use something else instead?

I am fine with removing it.

**Comment by brafdlog** [comment]
> About the file structure, I already started to reorg the project in [baruchiro/israeli-bank-scrapers-desktop#247](https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/247), but it is not important, since I think the most of my code will move to BudgetTrackingApp, or just gone, and the rest of the code is the `components` folder.

Ok, I updated the todo to be to remove the code that is no longer relevant when the ui starts using the budget tracking code.

**Comment by baruchiro** [comment]
About the Vue `vuex-persist`, I choose this way to save the `state` from the *Vuex* state manager to `configManager`, each time the state changes.

I think using the `configManager` itself in any place in the app is not a good way because in this way the config is not reactive.

The limitation of the `vuex-persist` way is that it act as a "side effect". I mean, if there is a problem when saving the state with `configManager`, it will affect the flow. In this case, you can use the app and you don't know that your changes are not saving in the file system.

**Comment by brafdlog** [comment]
But why do we need it to persist? We have the persisted state in the filesystem managed by the config manager, and we have the state in memory in the store that is the reflection of what is in the filesystem. Why do we need another layer of persistent state?
The app works with the state that is in the store so any change in the config in the store will cause the app to react. If we have a side effect that the store saves to the config manager on every change, we should have all we need. The additional layer of persisting the view store sounds error prone and I don't see the added value.
WDYT?

**Comment by brafdlog** [comment]
I think that is ok as long as if there is an error in persisting the config we show the error. This is basically optimistic UI which is quite a common pattern - the ui works as if the backend update succeeded even before it knows if it did, and if there was an error it shows it when it happens.

**Comment by brafdlog** [comment]
If in case of an error we refetch the data from the configManager (and show an error) we will only have a short time of inconsistent state

**Comment by baruchiro** [comment]
I added *Show error when `vuex-persist` failed, and re-fetch the config* task to this issue, because as I said, saving the config by `vuex-persist` is not in the main flow- it working in the background, so we need to register a callback or something.

(I wrote it under *TODOs*, but you can drag it to the other sections, it's very cool 🎉)

**Comment by baruchiro** [comment]
@brafdlog I created a new branch called [cleanIndex](https://github.com/brafdlog/budget-tracking/tree/cleanIndex), but it turns to be a very large change, so I leaving it, but I'm sharing with you what I learned.

I want to remove all the code from the root `index.ts`, to get a clear list about what the backend exporting. I have three (or more) points:

1. Move all the code from `index.ts` to separate files in a logical order. The **export** functionality should be in its file, the same with the **import** functionality, and the method that takes from **import** to **export** in another file. 
 In this way, we can validate (I hope there is lint for that) the `Vue` access only to the `@/originalBudgetTrackingApp`, and the backend itself access only to the [`flow`](https://github.com/brafdlog/budget-tracking/tree/cleanIndex/src/originalBudgetTrackingApp/flow) module, and this module uses its "internal" methods to import and export. 
 With this structure you can understand half of the code only by its module.
2. Inject sub-config to internal functions. The function should get only the relevant config, for example, the **export** function should get only the `outputVendors` part from the `Config`.
3. Separate types from the code. I have no much knowledge about best practices with TypeScript types declaration, but I think if we have a module with a lot of types declarations **and** more than small function, we should declare the types in a separated file.


I'm sure you share my thoughts, but I just wanted to document what I did, because it came out too big so I decided to stop for now.

**Comment by brafdlog** [comment]
I general I agree. For these types of things I suggest opening and issue and linking it to here so it will be easier to follow.

Next week I will have more time and one of the things I plan is to organize the open issues in a clearer way so we have a clearer view about where things stand and what are the open issues.

**Comment by baruchiro** [comment]
My suggestion is to create a new "board" for "pre-merge" issues.

**Comment by brafdlog** [comment]
@baruchiro I opened a project for the pre merge issues: https://github.com/brafdlog/budget-tracking/projects/4 and removed them from the description here.

Regarding the Todo's in the code, I suggest you open tickets for the ones you think we should handle and remove the ones we don't. We can sync on this if needed.

**Comment by brafdlog** [comment]
> @brafdlog I created a new branch called [cleanIndex](https://github.com/brafdlog/budget-tracking/tree/cleanIndex), but it turns to be a very large change, so I leaving it, but I'm sharing with you what I learned.
> 
> I want to remove all the code from the root `index.ts`, to get a clear list about what the backend exporting. I have three (or more) points:
> 
> 1. Move all the code from `index.ts` to separate files in a logical order. The **export** functionality should be in its file, the same with the **import** functionality, and the method that takes from **import** to **export** in another file.
>    In this way, we can validate (I hope there is lint for that) the `Vue` access only to the `@/originalBudgetTrackingApp`, and the backend itself access only to the [`flow`](https://github.com/brafdlog/budget-tracking/tree/cleanIndex/src/originalBudgetTrackingApp/flow) module, and this module uses its "internal" methods to import and export.
>    With this structure you can understand half of the code only by its module.
> 2. Inject sub-config to internal functions. The function should get only the relevant config, for example, the **export** function should get only the `outputVendors` part from the `Config`.
> 3. Separate types from the code. I have no much knowledge about best practices with TypeScript types declaration, but I think if we have a module with a lot of types declarations **and** more than small function, we should declare the types in a separated file.
> 
> I'm sure you share my thoughts, but I just wanted to document what I did, because it came out too big so I decided to stop for now.

Opened issues for 1 and 2: 
#89 
#90 

Regarding 3 its a matter of taste, we can discuss.

**Comment by brafdlog** [comment]
@baruchiro 
>  Make the node code expose an api as defined here

The current library code already exposes the config manager and the `scrapeAndUpdateOutputVendors` so I think we are good on that.

>  Update the electron UI flow to work with two main flows - configure, run scraping as defined here

We did implement those main flows except for the configuration of the category logic for which we have an issue - #31 

So I am marking those two as done
