### ISSUE TITLE
Remove the Contributors part or hide it in a Menu

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#87]

**Comment by giladtaase** [comment]
Are you going to keep the top menu of the app window? If you do, maybe we can add the credits under "Help/About".

**Comment by baruchiro** [comment]
In general, we are planning to re-think the whole UI.
So please do not take any current UI decisions as long term decisions.

But my suggestion is to think about **components**.
Even if we are thinking to change the UI, we still can decide if we want an **area** for "About", so you can start to create this "area" as **component** and put it somewhere. After the UI change, we will just put it in another place.

But since this is your first contribution, maybe it will be better to just remove the Contributors.

@brafdlog Need you here.

**Comment by giladtaase** [comment]
> In general, we are planning to re-think the whole UI.
> So please do not take any current UI decisions as long term decisions.
> 
> But my suggestion is to think about **components**.
> Even if we are thinking to change the UI, we still can decide if we want an **area** for "About", so you can start to create this "area" as **component** and put it somewhere. After the UI change, we will just put it in another place.
> 
> But since this is your first contribution, maybe it will be better to just remove the Contributors.
> 
> @brafdlog Need you here.

Sure I can remove.
I don't know electron yet, but my guess is that the top menus are not part of the web content. So if we decide to keep the menus and add the info there, there's no point in creating a web component.

**Comment by brafdlog** [comment]
@giladtaase welcome 🙂

As @baruchiro wrote this ui will undergo a significant change.

Currently our main goal is to have a functioning app that we can merge and release as a beta version. We will iterate on further improvements after we have a working version. 

Since this a small chunk of ui that would be easy to create again in a newer design, I think we should just remove it at this stage.

**Comment by giladtaase** [comment]
No problem I'll remove it.
